main: com.rooxchicken.outback.Outback
name: OutbackPlugin
version: 0.1
api-version: '1.20'

commands:
   resetcooldown:
      description: Resets the cooldown
      usage: /resetcooldown
   printname:
      description: Prints the current item name
      usage: /printname
   giveitems:
      description: Gives all of the custom items
      usage: /giveitems
      